# Generated by Django 5.2.12 on 2026-04-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=50, unique=True)),
                ('books_data', models.JSONField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
